name: Build Gradle and Publish Docker image

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle wrapper
        run: ./gradlew build

      - name: Upload all artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jars
          path: |
            bukkit/loader/build/libs/LuckPerms-Bukkit-*.jar
            bukkit-legacy/loader/build/libs/LuckPerms-Bukkit-Legacy-*.jar
            bungee/loader/build/libs/LuckPerms-Bungee-*.jar
            sponge/loader/build/libs/LuckPerms-Sponge-*.jar
            nukkit/loader/build/libs/LuckPerms-Nukkit-*.jar
            velocity/build/libs/LuckPerms-Velocity-*.jar
            fabric/build/libs/LuckPerms-Fabric-*.jar
            forge/loader/build/libs/LuckPerms-Forge-*.jar
            standalone/loader/build/libs/LuckPerms-Standalone-*.jar

      - name: Upload standalone artifact
        uses: actions/upload-artifact@v3
        with:
          name: standalone-binary
          path: standalone/loader/build/libs/LuckPerms-Standalone-*.jar
